/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProductionLinesRouteImport } from './routes/production-lines'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as MaterialPosRouteImport } from './routes/material-pos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyUpdatesRouteImport } from './routes/daily-updates'
import { Route as DailyLogsRouteImport } from './routes/daily-logs'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AdminToolsRouteImport } from './routes/admin-tools'
import { Route as IndexRouteImport } from './routes/index'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionLinesRoute = ProductionLinesRouteImport.update({
  id: '/production-lines',
  path: '/production-lines',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialPosRoute = MaterialPosRouteImport.update({
  id: '/material-pos',
  path: '/material-pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyUpdatesRoute = DailyUpdatesRouteImport.update({
  id: '/daily-updates',
  path: '/daily-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyLogsRoute = DailyLogsRouteImport.update({
  id: '/daily-logs',
  path: '/daily-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/admin-tools',
  path: '/admin-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-tools': typeof AdminToolsRoute
  '/approvals': typeof ApprovalsRoute
  '/customers': typeof CustomersRoute
  '/daily-logs': typeof DailyLogsRoute
  '/daily-updates': typeof DailyUpdatesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/material-pos': typeof MaterialPosRoute
  '/materials': typeof MaterialsRoute
  '/production-lines': typeof ProductionLinesRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-tools': typeof AdminToolsRoute
  '/approvals': typeof ApprovalsRoute
  '/customers': typeof CustomersRoute
  '/daily-logs': typeof DailyLogsRoute
  '/daily-updates': typeof DailyUpdatesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/material-pos': typeof MaterialPosRoute
  '/materials': typeof MaterialsRoute
  '/production-lines': typeof ProductionLinesRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-tools': typeof AdminToolsRoute
  '/approvals': typeof ApprovalsRoute
  '/customers': typeof CustomersRoute
  '/daily-logs': typeof DailyLogsRoute
  '/daily-updates': typeof DailyUpdatesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/material-pos': typeof MaterialPosRoute
  '/materials': typeof MaterialsRoute
  '/production-lines': typeof ProductionLinesRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-tools'
    | '/approvals'
    | '/customers'
    | '/daily-logs'
    | '/daily-updates'
    | '/dashboard'
    | '/login'
    | '/material-pos'
    | '/materials'
    | '/production-lines'
    | '/purchase-orders'
    | '/reports'
    | '/users'
    | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-tools'
    | '/approvals'
    | '/customers'
    | '/daily-logs'
    | '/daily-updates'
    | '/dashboard'
    | '/login'
    | '/material-pos'
    | '/materials'
    | '/production-lines'
    | '/purchase-orders'
    | '/reports'
    | '/users'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/admin-tools'
    | '/approvals'
    | '/customers'
    | '/daily-logs'
    | '/daily-updates'
    | '/dashboard'
    | '/login'
    | '/material-pos'
    | '/materials'
    | '/production-lines'
    | '/purchase-orders'
    | '/reports'
    | '/users'
    | '/vendors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminToolsRoute: typeof AdminToolsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CustomersRoute: typeof CustomersRoute
  DailyLogsRoute: typeof DailyLogsRoute
  DailyUpdatesRoute: typeof DailyUpdatesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MaterialPosRoute: typeof MaterialPosRoute
  MaterialsRoute: typeof MaterialsRoute
  ProductionLinesRoute: typeof ProductionLinesRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  ReportsRoute: typeof ReportsRoute
  UsersRoute: typeof UsersRoute
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-lines': {
      id: '/production-lines'
      path: '/production-lines'
      fullPath: '/production-lines'
      preLoaderRoute: typeof ProductionLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-pos': {
      id: '/material-pos'
      path: '/material-pos'
      fullPath: '/material-pos'
      preLoaderRoute: typeof MaterialPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-updates': {
      id: '/daily-updates'
      path: '/daily-updates'
      fullPath: '/daily-updates'
      preLoaderRoute: typeof DailyUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-logs': {
      id: '/daily-logs'
      path: '/daily-logs'
      fullPath: '/daily-logs'
      preLoaderRoute: typeof DailyLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-tools': {
      id: '/admin-tools'
      path: '/admin-tools'
      fullPath: '/admin-tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminToolsRoute: AdminToolsRoute,
  ApprovalsRoute: ApprovalsRoute,
  CustomersRoute: CustomersRoute,
  DailyLogsRoute: DailyLogsRoute,
  DailyUpdatesRoute: DailyUpdatesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MaterialPosRoute: MaterialPosRoute,
  MaterialsRoute: MaterialsRoute,
  ProductionLinesRoute: ProductionLinesRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  ReportsRoute: ReportsRoute,
  UsersRoute: UsersRoute,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
